print("Program starting.")
brand = input("Insert car brand: ")
model = input("Insert car model: ")
print("Car brand is", f'"{brand}"', "and the model is", sep=" ", end=" ")
print(f"'{model}'.", end="\n")
print("Program ending.")