print ("Program starting.")
print()
word = input("Insert a closed compound word: ")
print(f"The word you inserted is '{word}' and in reverse it is '{word[::-1]}'.")
print(f"The inserted word length is {len(word)}")
print(f"The last character is '{word[-1]}'")
print()
print(f"Take substring from the inserted word by inserting...")
start = int(input("Start point: "))
end = int(input("Ending point: "))
step = int(input("Step size: "))
print()
print(f"The word '{word}' sliced to the defined substring is '{word[start:end:step]}'.")
print("Program ending.")

